#!/bin/bash
CHALLENGE=${CHALLENGE:-5}
if [ -d /plots ]; then
    chia plots add -d /plots
fi

chia configure --log-level "${LOGLEVEL:-DEBUG}"
chia start farmer-no-wallet
while true; do
    if [ -d /plots ]; then
        chia plots check -n ${CHALLENGE} -l
    fi
    sleep 1h
done
