#!/bin/bash
THREAD=${THREAD:-4}
PLOTSIZE=${PLOTSIZE:-32}
BUFFER=${BUFFER:-3389}
BUCKETS=${BUCKETS:-128}
FARMER_KEY=${FARMER_KEY}
POOL_KEY=${POOL_KEY}
NOBITFIELD=${NOBITFIELD}
PLOTNUM=${PLOTNUM:-1}
# Require version ^1.2
POOL_CONTRACT_ADDR=${POOL_CONTRACT_ADDR}
TMPDIR=${TMPDIR:-/tmp/}
TMPDIR2=${TMPDIR2:-/tmp/}
PLOTDIR=${PLOTDIR:-/plots/}
# Madmax only
WAITFORCOPY=${WAITFORCOPY:-1}

# Control
USEMADMAX=${USEMADMAX:-0}
CLEAR_TMP=${CLEAR_TMP:-1}

chia init
if [ ! -d "${PLOTDIR}" ]; then
    echo "/plots directory not exist"
    exit 1
fi

# Remove unfinished plots, specific to .tmp file
if [ "${CLEAR_TMP}" -eq "1" ]; then
    ls -d ${TMPDIR}* | grep -P "plot.*.tmp$" | xargs -r -d "\n" rm
    ls -d ${TMPDIR2}* | grep -P "plot.*.tmp$" | xargs -r -d "\n" rm
fi

# Check if target disk have sufficient space, size in K
SPACELEFT=$(df "${PLOTDIR}" | tail -n +2 |  awk '{ print $4 }')
if [ "${SPACELEFT}" -lt "120000000" ]; then
    echo "${PLOTDIR} doesn't have enough space left ( <120GB )"
    exit 1
fi

# Remove unfinished copy plot by chia
ls -d ${PLOTDIR}* | grep -P "plot.*.tmp$" | xargs -r -d "\n" rm

# Move finished plots to plotdir if exist
# Might be cause by power outage
ls -d ${TMPDIR}* | grep -P "plot.*.plot$" | xargs -I {} -r -d "\n" mv -f {} ${PLOTDIR}
ls -d ${TMPDIR2}* | grep -P "plot.*.plot$" | xargs -I {} -r -d "\n" mv -f {} ${PLOTDIR}

if [ ! -z "${NOBITFIELD}" ]; then
    NOBITFIELD="-e"
fi

if [ "${PLOTNUM}" -gt "0" ]; then
    PLOTNUM="-n ${PLOTNUM}"
else
    PLOTNUM=""
fi

if [ "${USEMADMAX}" -eq "1" ]; then
    COMMAND="/usr/local/bin/chia-plot-mm"
    if [ "${WAITFORCOPY}" -eq "1" ]; then
        WAITFORCOPY="--waitforcopy"
    fi
else
    COMMAND="/usr/local/bin/chia-plot plots create"
    WAITFORCOPY=""
fi

if [ -z ${FARMER_KEY} ]; then
    ${COMMAND} \
        -k ${PLOTSIZE} \
        -u ${BUCKETS} \
        -b ${BUFFER} \
        -r ${THREAD} \
        -t ${TMPDIR} \
        -2 ${TMPDIR2} \
        -d ${PLOTDIR} \
        ${PLOTNUM} \
        ${NOBITFIELD} \
        ${WAITFORCOPY}
else
    if [ -z ${POOL_CONTRACT_ADDR} ]; then
        ${COMMAND} \
            -k ${PLOTSIZE} \
            -u ${BUCKETS} \
            -b ${BUFFER} \
            -r ${THREAD} \
            -t ${TMPDIR} \
            -2 ${TMPDIR2} \
            -d ${PLOTDIR} \
            -p ${POOL_KEY} \
            -f ${FARMER_KEY} \
            ${PLOTNUM} \
            ${NOBITFIELD} \
            ${WAITFORCOPY}
    else
        ${COMMAND} \
            -k ${PLOTSIZE} \
            -u ${BUCKETS} \
            -b ${BUFFER} \
            -r ${THREAD} \
            -t ${TMPDIR} \
            -2 ${TMPDIR2} \
            -d ${PLOTDIR} \
            -c ${POOL_CONTRACT_ADDR} \
            -f ${FARMER_KEY} \
            ${PLOTNUM} \
            ${NOBITFIELD} \
            ${WAITFORCOPY}
    fi
fi
