#!/bin/bash
THREAD=${THREAD:-4}
PLOTSIZE=${PLOTSIZE:-32}
BUFFER=${BUFFER:-3389}
BUCKETS=${BUCKETS:-128}
FARMER_KEY=${FARMER_KEY}
POOL_KEY=${POOL_KEY}
CLEAR_TMP=${CLEAR_TMP:-1}
NOBITFIELD=${NOBITFIELD}
DELAY=${DELAY:-0}
PLOTNUM=${PLOTNUM:-1}
# Require version ^1.2
POOL_CONTRACT_ADDR=${POOL_CONTRACT_ADDR}

chia init
if [ ! -d /plots ]; then
    echo "/plots directory not exist"
    exit 1
fi

# Remove unfinished plots, specific to .tmp file
if [ "${CLEAR_TMP}" -eq "1" ]; then
    ls -d /tmp/* | grep -P "plot.*.tmp$" | xargs -d "\n" rm
fi

# Check if target disk have sufficient space, size in K
SPACELEFT=$(df /plots | tail -n +2 |  awk '{ print $4 }')
if [ "${SPACELEFT}" -lt "120000000" ]; then
    echo "/plots doesn't have enough space left ( <120GB )"
    exit 1
fi

if [ ! -z "${NOBITFIELD}" ]; then
    NOBITFIELD="-e"
fi

if [ "${PLOTNUM}" -gt "0" ]; then
    PLOTNUM="-n ${PLOTNUM}"
else
    PLOTNUM=""
fi

sleep ${DELAY}
if [ -z ${FARMER_KEY} ]; then
    chia plots create -k ${PLOTSIZE} -u ${BUCKETS} -b ${BUFFER} -r ${THREAD} ${PLOTNUM} ${NOBITFIELD} -t /tmp -d /plots
else
    if [ -z ${POOL_CONTRACT_ADDR} ]; then
        chia plots create -k ${PLOTSIZE} -u ${BUCKETS} -b ${BUFFER} -r ${THREAD} ${PLOTNUM} ${NOBITFIELD} -t /tmp -d /plots -p ${POOL_KEY} -f ${FARMER_KEY}
    else
        chia plots create -k ${PLOTSIZE} -u ${BUCKETS} -b ${BUFFER} -r ${THREAD} ${PLOTNUM} ${NOBITFIELD} -t /tmp -d /plots -c ${POOL_CONTRACT_ADDR} -f ${FARMER_KEY}
    fi
fi
