#!/bin/bash
CHALLENGE=${CHALLENGE:-5}
FARMERCA=${FARMERCA:-/home/chia/farmer-ca}

if [ -d "${FARMERCA}" ]; then
    chia init -c "${FARMERCA}"
fi
if [ -d /plots ]; then
    chia plots add -d /plots
fi
chia configure --set-farmer-peer ${FARMER_ADDR}:${FARMER_PORT}
chia start harvester
if [ -d /plots ]; then
    chia plots check -n ${CHALLENGE} -l
fi
while true; do
    sleep 1m
done
